{{- if .Values.ingress.enabled -}}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-staging
  name: {{ include "customer-list-service.fullname" . }}
spec:
  ingressClassName: nginx
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - backend:
          service:
            name: {{ include "customer-list-service.fullname" . }}
            port:
              number: {{ .Values.service.port }}
        path: /
        pathType: Prefix
{{- if .Values.ingress.tls }}
  tls:
  - hosts:
    - {{ .Values.ingress.host }}
    secretName: {{ include "customer-list-service.fullname" . }}-tls
{{- end -}}
{{- end -}}
